name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.multipaper.worldguardsyncer.WorldGuardSyncerPlugin
author: PureGero
api-version: 1.18
depend: [ WorldGuard ]